### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by gwenf** [Free-Code-Camp-Indy/free-code-camp-indy.github.io#11]
![img_9093](https://cloud.githubusercontent.com/assets/10039233/19545003/ecf5b5ca-9650-11e6-88d1-49ef48ebdf95.JPG)

**Comment by mattattaq** [comment]
Designers:
Your mission is to get pictures of the community leaders:
-Gwen
-Kim
-Jared
-Matthew

Also we need to craft our 2 sentence mission statement, gather pictures of places we meet, and gather the code of conduct from FCC.

Developers:
Your mission is to place the content as shown in the picture above. There are four sections:
-Mission Statement
-Places we meet
-Community leaders
-code of conduct
    *Link to the google form to report or contact our group.

**Comment by gwenf** [comment]
Mission Statement: We are a community organization aimed at teaching, encouraging, and supporting people who want to learn to web development.

**Comment by larrytooley** [comment]
@gwenf I prefer it with one less "to".
"We are a community organization aimed at teaching, encouraging, and supporting people who want to learn web development."

**Comment by gwenf** [comment]
I think this is good. We might want to update the styling later on.
