### ISSUE TITLE
Report Problems Form/Contact

### ISSUE THREAD

**Issue by gwenf** [Free-Code-Camp-Indy/free-code-camp-indy.github.io#13]
![img_9092](https://cloud.githubusercontent.com/assets/10039233/19544733/0ca4acf2-964f-11e6-91dc-a2ab43491b10.JPG)

**Comment by mattattaq** [comment]
I believe we can embed a google form (something basic looking so it fits our design) and the email would go to: freecodecampindy@gmail.com

Whomever takes this task talk to me or gwen to get the login credentials to set this up.
We'd also like to setup auto-forwarding to the admins so we all have visibility on the forwards. So this isn't a particularly sexy task but also necissary.

**Comment by gwenf** [comment]
Style Guide: https://docs.google.com/document/d/1gJOjeVYkxAT22jDIIkzZSfJR3Vtgo-6lTEj1tOhIHlM/edit

**Comment by gwenf** [comment]
This page is completed for a while now.
