### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by gwenf** [Free-Code-Camp-Indy/free-code-camp-indy.github.io#2]
Let's post some pics and start discussing how we will build this page.

**Comment by Firearrow5235** [comment]
"Blogger of the Month" section should have a "Check out more blogs!" link, which links to the "Blogs" section of the website.

**Comment by gwenf** [comment]
We sectioned off the home page into four parts, each with an issue

**Comment by mattattaq** [comment]
This task is putting together all the pieces. This can only be complete after the api, nav, footer, and content are crystallized.

**Comment by gwenf** [comment]
The pieces are all assembled now.
