### ISSUE TITLE
Meetup API

### ISSUE THREAD

**Issue by larrytooley** [Free-Code-Camp-Indy/free-code-camp-indy.github.io#3]
Use meetup API to pull in the previous meetup, the next meetup, and the meetup after that. This will be displayed on the home page immediately below the welcome section.  The three will be displayed as three boxes.

https://www.meetup.com/meetup_api/

**Comment by gwenf** [comment]
@larrytooley @aallbrig What else needs to be done on this? It's not updating with the current meetup. Plus the layout needs some updates.

Let me know where you are at and if I can help.
