### ISSUE TITLE
Add in google analytics

### ISSUE THREAD

**Issue by aallbrig** [Free-Code-Camp-Indy/free-code-camp-indy.github.io#30]
We should add in google analytics to the site in order to collect data on traffic to the site.

We need a trusted administrator (@gwen? @TheJaredWilcurt? @mattattaq?) to

- [x] Log into google analytics
- [x] Generate a google analytics snippet
- [x] Add this snippet to all pages (preferably as a `data-include` statement or other "include partial into pages" pattern)
- [ ] Add the emails of all participants so they can also view the data

Edit: ordered list -> task list, marked "generate google analytics snippet" as complete; thanks @TheJaredWilcurt

**Comment by TheJaredWilcurt** [comment]
```html
<script>
  (function(F,C,c,I,n,d,y){F['GoogleAnalyticsObject']=n;F[n]=F[n]||function(){
  (F[n].q=F[n].q||[]).push(arguments)},F[n].l=1*new Date();d=C.createElement(c),
  y=C.getElementsByTagName(c)[0];d.async=1;d.src=I;y.parentNode.insertBefore(d,y)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-88092218-1', 'auto');
  ga('send', 'pageview');
</script>
```

**Comment by gwenf** [comment]
Just need to add the emails of participants I think
