### ISSUE TITLE
Integrate AWS lambda FN into site

### ISSUE THREAD

**Issue by aallbrig** [Free-Code-Camp-Indy/free-code-camp-indy.github.io#34]
This issue is part two of two issues, where the first issue is located here: https://github.com/Free-Code-Camp-Indy/free-code-camp-indy.github.io/issues/33.  https://github.com/Free-Code-Camp-Indy/free-code-camp-indy.github.io/issues/33 must be complete before this issue can be worked on.

Once the AWS Lambda element has been created, we must then integrate it into the site.  This entails removing "generate and use mock JSON" code created in https://github.com/Free-Code-Camp-Indy/free-code-camp-indy.github.io/pull/18, https://github.com/Free-Code-Camp-Indy/free-code-camp-indy.github.io/pull/26, and https://github.com/Free-Code-Camp-Indy/free-code-camp-indy.github.io/pull/27 and sending a request out to the AWS system for meetup event data.

There may be CORs concerns to be concerned about.

Once this two part issue is resolved, https://github.com/Free-Code-Camp-Indy/free-code-camp-indy.github.io/issues/3 can be closed.

**Comment by gwenf** [comment]
Closed because of inactivity. Feel free to reopen.
