### ISSUE TITLE
Footer alignment is off

### ISSUE THREAD

**Issue by gwenf** [Free-Code-Camp-Indy/free-code-camp-indy.github.io#44]
The links column and the meetup display box are not lined up properly.

**Comment by klcantrell** [comment]
Hiya, I'd like to take a shot at this one if it's still on the table

**Comment by klcantrell** [comment]
See below for pics of what the footer currently looks like vs. what I have proposed

#### current

##### full laptop width
![current_laptop-width](https://user-images.githubusercontent.com/24497389/40579637-1783c960-60fa-11e8-9191-313ab14c1f5b.JPG)

##### below 800px
![current_below-800](https://user-images.githubusercontent.com/24497389/40579643-49f5c18c-60fa-11e8-983d-9c47a21b0b51.JPG)

#### proposed

##### full laptop width
![proposed_laptop-width](https://user-images.githubusercontent.com/24497389/40579644-62393c2e-60fa-11e8-8431-4aaaaa9cf01d.JPG)

##### below 800
![proposed_below-800](https://user-images.githubusercontent.com/24497389/40579645-6a9372ae-60fa-11e8-8216-aad26e60fc3e.JPG)

**Comment by mattattaq** [comment]
Proposal looks good, submit a pr and i'll take a look
