### ISSUE TITLE
Tile size

### ISSUE THREAD

**Issue by mattattaq** [Free-Code-Camp-Indy/free-code-camp-indy.github.io#48]
![screen shot 2018-05-23 at 12 20 04 pm](https://user-images.githubusercontent.com/13422887/40437582-b4e061ec-5e83-11e8-8fab-9fed23a50d98.png)
* Bottom margin is too long
* Top margin between FCC Meetups and top is too long
* Size of the tile is rather large, especially on mobile
* Height of tile is an issue, too big

Note: Could use a redesign, it's a good first attempt but wasn't fully realized. We should improve this version before we iterate on v2 or if we even want a v2.

**Comment by klcantrell** [comment]
I'd like to take a stab at this.  I don't think I can make myself an assignee so wanted to at least lay claim to it here if that is alright.

@mattattaq let me know if I can proceed.  I can have something ready for review today.
