### ISSUE TITLE
Campers-Blogs

### ISSUE THREAD

**Issue by Firearrow5235** [Free-Code-Camp-Indy/free-code-camp-indy.github.io#7]

**Comment by gwenf** [comment]
![img_9090](https://cloud.githubusercontent.com/assets/10039233/19544908/425fb598-9650-11e6-9641-b4686e7316f3.JPG)

**Comment by gwenf** [comment]
Style Guide: https://docs.google.com/document/d/1gJOjeVYkxAT22jDIIkzZSfJR3Vtgo-6lTEj1tOhIHlM/edit

**Comment by gwenf** [comment]
List of all camper blogs from our local group.

**Comment by gwenf** [comment]
Here is a list of the blogs I have:
Lorian Bates - https://locodesblog.wordpress.com/2016/08/04/polymorphic-me/
Larry Tooley - http://damagedtechnologies.com
Gavyn Leavitt - https://gavsdevblog.wordpress.com/
Matthew David - https://mattattaqdevblog.wordpress.com/
J.T. Maupin - https://jmsmaupin.wordpress.com/
Gwendolyn Faraday - http://gwenfaraday.com/LearningCode/
Kimberly Sharpe - http://kimmihack.blogspot.com/
McKinnely Bentley - http://mbcodeguy.blogspot.com/
Nicholas Gillespie - http://programpractical.com/

**Comment by gwenf** [comment]
I think this is complete.
