### ISSUE TITLE
Home Page - Welcome Section

### ISSUE THREAD

**Issue by gwenf** [Free-Code-Camp-Indy/free-code-camp-indy.github.io#8]
Refer to home page picture in the style guide:
https://docs.google.com/document/d/1PBaRWUjsR6IVD2P5Tz7H1N6wzE8awM7oETdUfBA9o1Q/edit

**Comment by mattattaq** [comment]
The welcome section consists of:
-cool banner
-Welcome message
-Featured section (we can give different classes for different features like blog, event, someone got a job, etc.)

**Comment by mattattaq** [comment]
**Here is a link to the style guide:**
https://docs.google.com/document/d/1gJOjeVYkxAT22jDIIkzZSfJR3Vtgo-6lTEj1tOhIHlM/edit?usp=sharing
**FCC Info doc:**
https://docs.google.com/document/d/1PBaRWUjsR6IVD2P5Tz7H1N6wzE8awM7oETdUfBA9o1Q/edit?usp=sharing

**Comment by gwenf** [comment]
@mattattaq Any update on the banner status?

**Comment by gwenf** [comment]
The banner we have looks good for now. We can always update it in the future.
